- hosts: all
  become: yes
  become_method: sudo
  remote_user: ubuntu

  vars:
    dir: /home/ubuntu/
    app_dir: /home/ubuntu/yummy_react
    ansible_python_interpreter: "/usr/bin/python3"

  roles:
    - essentials
    - nginx
    - jenkins
    - aws
    - kubernetes
    - docker
    - supervisor
