---
############### aws ######################

- name: Install awscli and jq
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
    - jq

- name: Create credentials
  environment: 
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    AWS_DEFAULT_REGION: us-east-2
  shell: |
    mkdir -p .aws/
    printf "
    [default]
    region=$AWS_DEFAULT_REGION
    output=json
    " > config && sudo chmod 0644 config && sudo mv -f config .aws/
    
    printf "
    [default]
    aws_access_key_id=$AWS_ACCESS_KEY_ID
    aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
    " > credentials && sudo chmod 0644 credentials && sudo mv -f credentials .aws/

- name: Make kube script executable
  shell: |
    chmod +x /home/ubuntu/kube.sh
