---
################# docker ########################

- name: Docker setup
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    apt-cache policy docker-ce
    sudo apt-get install -y docker-ce
    sudo systemctl status docker
    sudo usermod -aG docker ${USER}
    sudo gpasswd -a jenkins docker
    sudo service docker restart
    sudo chmod 777 /var/run/docker.sock

- name: Download mailhog
  shell: |
    docker pull mailhog/mailhog
    docker run --restart unless-stopped --name mailhog -p 1025:1025 -p 8025:8025 -d mailhog/mailhog
